name: Feature request
description: Suggest an idea to improve NEFB
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Focus on the user problem first; solutions second.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What's the user problem or job-to-be-done?
      placeholder: As a [role], I want … so that …
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: MVP-friendly (keeps the tool simple)
        - label: Nice-to-have (post-MVP)
        - label: Requires new platform/API permissions
